# Generated by Django 4.1.5 on 2023-01-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='driving_licence',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
