# Generated by Django 4.1.5 on 2023-01-23 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pickup_location', models.CharField(max_length=50)),
                ('dropoff_location', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_per_day', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('vehicle_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatchback'), ('SUV', 'SUV')], default='SEDAN', max_length=10)),
                ('fuel_type', models.CharField(choices=[('GAS', 'Gas'), ('ELECTRIC', 'Electric')], default='GAS', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='rental',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle'),
        ),
    ]
