# Generated by Django 4.1.5 on 2023-01-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rating_rental_vehicle_delete_user_rental_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='has_air_conditioning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='MANUAL', max_length=10),
        ),
    ]
