# Generated by Django 4.1.5 on 2023-01-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vehicle_has_air_conditioning_vehicle_transmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='transmission',
            new_name='transmission_type',
        ),
    ]
