# Generated by Django 4.1.5 on 2023-01-23 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_rental_end_date_alter_rental_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='dropoff_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_location', to='main.location'),
        ),
    ]
