# Generated by Django 4.1.5 on 2023-01-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_rental_dropoff_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
