# Generated by Django 4.1.5 on 2023-01-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rental_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(default='No comment for this rental. Sorry!', max_length=300),
        ),
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='rating_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rating'),
        ),
    ]
