# Generated by Django 4.1.5 on 2023-01-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rating_comment_rating_value_rental_rating_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='user_comments',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
